name: mac_whisper
description: A subtitle editor for macOS

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.0
  video_player: ^2.8.2
  path: ^1.8.3
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  desktop_drop: ^0.4.4
  cross_file: ^0.3.3+6
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
